Generated the ros package using catkin
iscumd/obstacle_detection pull request #2
Opened 2018-02-24 19:25 UTC by airfield20

I regenerated the package using catking and refactored the includes. We probably should set an include directory in cmake in the future. For now the includes are ../include/file.h. 

The pull does not build. The original didnt have any build system included so it did not build either. Ill fix the build issues in the next pull.

2018-02-24 19:57 UTC, airfield20 commented
This will fix #1

2018-02-24 21:51 UTC, airfield20 commented on CMakeLists.txt
> +# include
Just testing githubs code review functionality

2018-02-24 21:51 UTC, airfield20 commented on CMakeLists.txt
> +# include
Uncomment this

2018-02-24 21:51 UTC, airfield20 commented on CMakeLists.txt
> +#   Service1.srv
May need to use this in the future if we use a map service

2018-02-26 19:01 UTC, davidcutting requested changes
Thanks for fixing the ROS set-up. I totally forgot about that. Here are my thoughts on your other changes:

- Why make our own Point2D? ROS has one built in. Functions which are a part of the point class should be members of Obstacle.

- Instead of "position()," use "get_position()" to match the "set_position()." As a general note, we should probably agree on our naming conventions and commenting requirements. Ex: "getPosition()" or "get_position()."

- I prefer separating obstacletype and obstacle into their own files. One file per header.

- RectangleBoundary should just be a type of obstacle, because it uses the same format as an obstacle anyway. Making it part of it's own class is redundant.

- Renaming the files to reflect the class name would make them easier to find and include.

2018-02-26 20:56 UTC, airfield20 commented
`Why make our own Point2D? ROS has one built in. Functions which are a part of the point class should be members of Obstacle.`
Using the ros point makes all of code dependent on our libraries dependent on ros. If we decide to switch to another communications marshaling library it will require a rewrite.


`Instead of "position()," use "get_position()" to match the "set_position()." As a general note, we should probably agree on our naming conventions and commenting requirements. Ex: "getPosition()" or "get_position()."`
I don't have an issue with this. removing get from every function name makes it easier to use autocomplete, change if you want. I dont mind, just be consistent across all of the files, in this node.


`I prefer separating obstacletype and obstacle into their own files. One file per header.` 
If you look at STL or boost, things directly related to each other are put into the same header file. Ex: std::unordered_set and std::set are in the same header. Again I dont mind if you change it.

 `RectangleBoundary should just be a type of obstacle, because it uses the same format as an obstacle anyway. Making it part of it's own class is redundant.`
RectangleBoundary shouldnt be a type of obstacle, we should actually also have a boundary type be typedef as a std::vector<ISC::Point2D> to represent a polygon that defines our course. These can be included in the same header. A boundary isnt an obstacle because its not tangible. Its not a physical object you are avoiding but rather a software defined point that shouldnt be exceeded. These two things will be handled differently in code, thus should be separate.

`Renaming the files to reflect the class name would make them easier to find and include.` 
Go ahead and change, not a problem to me.

2018-02-26 20:57 UTC, airfield20 commented on include/boundary.h
> -#include "geometry_msgs/Point.h"
This makes our code ros dependent. Lets avoid doing this

2018-02-26 20:58 UTC, airfield20 commented on src/obstacle_detection.cpp
> -float angle_min; // minimum angle possible
no global variables...

2018-02-26 21:00 UTC, airfield20 commented on src/obstacle_detection.cpp
> -float* ranges; // list of distance 'r' from each measured point
Dont ever do this. Most segfaults are caused by indexing issues. 
For arrays use std::array E.g.
std::array ranges;
to get/set values use at()
ranges.at(0) = 5;
int var = ranges.at(3);

2018-02-26 21:01 UTC, airfield20 commented on src/obstacle_detection.cpp
> -
All of this stuff should be in class, Ill talk to you guys about it tomorrow

2018-02-26 21:03 UTC, airfield20 commented on src/obstacle_detection.cpp
> -#include "geometry_msgs/Point.h"
Lets try not to pull things that don't build. I havent tested this version, but just as a general rule

2018-02-26 23:43 UTC, emmaskychuks commented on include/obstacle_detection/obstacle.h
> +            void set_interior_points(const std::vector<Point2D> interior_points);
Pass by reference

2018-02-26 23:46 UTC, emmaskychuks commented on include/obstacle_detection/point.h
> +            geometry_msgs::Point to_ros_point() const;
Convert to Point32

2018-02-26 23:47 UTC, emmaskychuks commented on include/obstacle_detection/point.h
> +        bool close_enough(Point2D p1, Point2D p2, double threshold);
All params should be const references

2018-02-27 00:05 UTC, emmaskychuks commented on include/obstacle_detection/boundary.h
> +        class RectangleBoundary {
Change RectangleBoundary2D

2018-02-27 00:32 UTC, merged